
var Module = (() => {
  var _scriptName = import.meta.url;
  
  return (
async function(moduleArg = {}) {
  var moduleRtn;

var f=moduleArg,aa,r,ba=new Promise((a,b)=>{aa=a;r=b}),ca="object"==typeof window,t="function"==typeof importScripts,u="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node;if(u){const {createRequire:a}=await import("module");var require=a(import.meta.url)}var da=Object.assign({},f),x="",ea,A;
if(u){var fs=require("fs"),fa=require("path");x=require("url").fileURLToPath(new URL("./",import.meta.url));A=a=>{a=B(a)?new URL(a):fa.normalize(a);return fs.readFileSync(a)};ea=a=>{a=B(a)?new URL(a):fa.normalize(a);return new Promise((b,c)=>{fs.readFile(a,void 0,(d,e)=>{d?c(d):b(e.buffer)})})};process.argv.slice(2)}else if(ca||t)t?x=self.location.href:"undefined"!=typeof document&&document.currentScript&&(x=document.currentScript.src),_scriptName&&(x=_scriptName),x.startsWith("blob:")?
x="":x=x.substr(0,x.replace(/[?#].*/,"").lastIndexOf("/")+1),t&&(A=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ea=a=>B(a)?new Promise((b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{(200==d.status||0==d.status&&d.response)&&c(d.response);b(d.status)};d.onerror=b;d.send(null)}):fetch(a,{credentials:"same-origin"}).then(b=>b.ok?b.arrayBuffer():Promise.reject(Error(b.status+
" : "+b.url)));f.print||console.log.bind(console);var C=f.printErr||console.error.bind(console);Object.assign(f,da);da=null;var D;f.wasmBinary&&(D=f.wasmBinary);var F,ha=!1,ia,G,H,I,K,L,ja,ka;function la(){var a=F.buffer;f.HEAP8=ia=new Int8Array(a);f.HEAP16=H=new Int16Array(a);f.HEAPU8=G=new Uint8Array(a);f.HEAPU16=I=new Uint16Array(a);f.HEAP32=K=new Int32Array(a);f.HEAPU32=L=new Uint32Array(a);f.HEAPF32=ja=new Float32Array(a);f.HEAPF64=ka=new Float64Array(a)}var ma=[],na=[],pa=[];
function qa(){var a=f.preRun.shift();ma.unshift(a)}var M=0,ra=null,N=null;function sa(a){f.onAbort?.(a);a="Aborted("+a+")";C(a);ha=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");r(a);throw a;}var ta=a=>a.startsWith("data:application/octet-stream;base64,"),B=a=>a.startsWith("file://"),ua;function va(a){if(a==ua&&D)return new Uint8Array(D);if(A)return A(a);throw"both async and sync fetching of the wasm failed";}
function wa(a){return D?Promise.resolve().then(()=>va(a)):ea(a).then(b=>new Uint8Array(b),()=>va(a))}function xa(a,b,c){return wa(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{C(`failed to asynchronously prepare wasm: ${d}`);sa(d)})}
function ya(a,b){var c=ua;return D||"function"!=typeof WebAssembly.instantiateStreaming||ta(c)||B(c)||u||"function"!=typeof fetch?xa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){C(`wasm streaming compile failed: ${e}`);C("falling back to ArrayBuffer instantiation");return xa(c,a,b)}))}var za=a=>{for(;0<a.length;)a.shift()(f)};class Aa{constructor(a){this.D=a-24}}
var Ba=0,Ca=0,Da,O=a=>{for(var b="";G[a];)b+=Da[G[a++]];return b},P={},Q={},R={},S,Ea=a=>{throw new S(a);},Fa,Ga=(a,b)=>{function c(g){g=b(g);if(g.length!==d.length)throw new Fa("Mismatched type converter count");for(var m=0;m<d.length;++m)T(d[m],g[m])}var d=[];d.forEach(function(g){R[g]=a});var e=Array(a.length),k=[],l=0;a.forEach((g,m)=>{Q.hasOwnProperty(g)?e[m]=Q[g]:(k.push(g),P.hasOwnProperty(g)||(P[g]=[]),P[g].push(()=>{e[m]=Q[g];++l;l===k.length&&c(e)}))});0===k.length&&c(e)};
function Ha(a,b,c={}){var d=b.name;if(!a)throw new S(`type "${d}" must have a positive integer typeid pointer`);if(Q.hasOwnProperty(a)){if(c.G)return;throw new S(`Cannot register type '${d}' twice`);}Q[a]=b;delete R[a];P.hasOwnProperty(a)&&(b=P[a],delete P[a],b.forEach(e=>e()))}function T(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");return Ha(a,b,c)}
var Ia=[],U=[],Ja=a=>{9<a&&0===--U[a+1]&&(U[a]=void 0,Ia.push(a))},Ka=a=>{if(!a)throw new S("Cannot use deleted val. handle = "+a);return U[a]},La=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Ia.pop()||U.length;U[b]=a;U[b+1]=1;return b}};function Ma(a){return this.fromWireType(L[a>>2])}
var Na={name:"emscripten::val",fromWireType:a=>{var b=Ka(a);Ja(a);return b},toWireType:(a,b)=>La(b),argPackAdvance:8,readValueFromPointer:Ma,C:null},Oa=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(ja[c>>2])};case 8:return function(c){return this.fromWireType(ka[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},V=(a,b)=>Object.defineProperty(b,"name",{value:a}),Pa=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};
function Qa(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].C)return!0;return!1}function Ta(a){var b=Function;if(!(b instanceof Function))throw new TypeError(`new_ called with constructor type ${typeof b} which is not a function`);var c=V(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
for(var Ua=(a,b)=>{if(void 0===f[a].B){var c=f[a];f[a]=function(...d){if(!f[a].B.hasOwnProperty(d.length))throw new S(`Function '${b}' called with an invalid number of arguments (${d.length}) - expects one of (${f[a].B})!`);return f[a].B[d.length].apply(this,d)};f[a].B=[];f[a].B[c.F]=c}},Va=(a,b,c)=>{if(f.hasOwnProperty(a)){if(void 0===c||void 0!==f[a].B&&void 0!==f[a].B[c])throw new S(`Cannot register public name '${a}' twice`);Ua(a,a);if(f.hasOwnProperty(c))throw new S(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
f[a].B[c]=b}else f[a]=b,void 0!==c&&(f[a].I=c)},Wa=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(L[b+4*d>>2]);return c},Xa,Ya=(a,b,c=[])=>{a.includes("j")?(a=a.replace(/p/g,"i"),b=(0,f["dynCall_"+a])(b,...c)):b=Xa.get(b)(...c);return b},Za=(a,b)=>(...c)=>Ya(a,b,c),$a=(a,b)=>{a=O(a);var c=a.includes("j")?Za(a,b):Xa.get(b);if("function"!=typeof c)throw new S(`unknown function pointer with signature ${a}: ${b}`);return c},ab,cb=a=>{a=bb(a);var b=O(a);W(a);return b},db=(a,b)=>{function c(k){e[k]||Q[k]||(R[k]?
R[k].forEach(c):(d.push(k),e[k]=!0))}var d=[],e={};b.forEach(c);throw new ab(`${a}: `+d.map(cb).join([", "]));},eb=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?a.substr(0,b):a},fb=(a,b,c)=>{switch(b){case 1:return c?d=>ia[d]:d=>G[d];case 2:return c?d=>H[d>>1]:d=>I[d>>1];case 4:return c?d=>K[d>>2]:d=>L[d>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},gb="undefined"!=typeof TextDecoder?new TextDecoder:void 0,hb="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):
void 0,ib=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&I[c];)++c;c<<=1;if(32<c-a&&hb)return hb.decode(G.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=H[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},jb=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)H[b>>1]=a.charCodeAt(e),b+=2;H[b>>1]=0;return b-d},kb=a=>2*a.length,lb=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=K[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|
e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},mb=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var k=a.charCodeAt(e);if(55296<=k&&57343>=k){var l=a.charCodeAt(++e);k=65536+((k&1023)<<10)|l&1023}K[b>>2]=k;b+=4;if(b+4>c)break}K[b>>2]=0;return b-d},nb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},ob=[],pb=a=>{var b=ob.length;ob.push(a);return b},qb=(a,b)=>{var c=Q[a];if(void 0===c)throw a=`${b} has unknown type ${cb(a)}`,
new S(a);return c},rb=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=qb(L[b+4*d>>2],"parameter "+d);return c},sb=(a,b,c)=>{var d=[];a=a.toWireType(d,c);d.length&&(L[b>>2]=La(d));return a},tb=Array(256),X=0;256>X;++X)tb[X]=String.fromCharCode(X);Da=tb;S=f.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};Fa=f.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};U.push(0,1,void 0,1,null,1,!0,1,!1,1);
f.count_emval_handles=()=>U.length/2-5-Ia.length;ab=f.UnboundTypeError=((a,b)=>{var c=V(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
var vb={o:(a,b,c)=>{var d=new Aa(a);L[d.D+16>>2]=0;L[d.D+4>>2]=b;L[d.D+8>>2]=c;Ba=a;Ca++;throw Ba;},p:()=>{sa("")},n:()=>{},j:(a,b,c,d)=>{b=O(b);T(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,k){return k?c:d},argPackAdvance:8,readValueFromPointer:function(e){return this.fromWireType(G[e])},C:null})},i:a=>T(a,Na),g:(a,b,c)=>{b=O(b);T(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,argPackAdvance:8,readValueFromPointer:Oa(b,c),C:null})},h:(a,b,c,d,e,k,l)=>{var g=Wa(b,c);a=O(a);
a=eb(a);e=$a(d,e);Va(a,function(){db(`Cannot call ${a} due to unbound types`,g)},b-1);Ga(g,m=>{var h=[m[0],null].concat(m.slice(1));m=a;var n=a;var q=e,p=h.length;if(2>p)throw new S("argTypes array size mismatch! Must at least get return value and 'this' types!");var w=null!==h[1]&&!1,E=Qa(h),y="void"!==h[0].name;q=[n,Ea,q,k,Pa,h[0],h[1]];for(var v=0;v<p-2;++v)q.push(h[v+2]);if(!E)for(v=w?1:2;v<h.length;++v)null!==h[v].C&&q.push(h[v].C);E=Qa(h);v=h.length;var z="",J="";for(p=0;p<v-2;++p)z+=(0!==p?
", ":"")+"arg"+p,J+=(0!==p?", ":"")+"arg"+p+"Wired";z=`\n        return function (${z}) {\n        if (arguments.length !== ${v-2}) {\n          throwBindingError('function ' + humanName + ' called with ' + arguments.length + ' arguments, expected ${v-2}');\n        }`;E&&(z+="var destructors = [];\n");var Ra=E?"destructors":"null",oa="humanName throwBindingError invoker fn runDestructors retType classParam".split(" ");w&&(z+="var thisWired = classParam['toWireType']("+Ra+", this);\n");for(p=0;p<
v-2;++p)z+="var arg"+p+"Wired = argType"+p+"['toWireType']("+Ra+", arg"+p+");\n",oa.push("argType"+p);w&&(J="thisWired"+(0<J.length?", ":"")+J);z+=(y||l?"var rv = ":"")+"invoker(fn"+(0<J.length?", ":"")+J+");\n";if(E)z+="runDestructors(destructors);\n";else for(p=w?1:2;p<h.length;++p)w=1===p?"thisWired":"arg"+(p-2)+"Wired",null!==h[p].C&&(z+=`${w}_dtor(${w});\n`,oa.push(`${w}_dtor`));y&&(z+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");let [Sa,wb]=[oa,z+"}\n"];Sa.push(wb);h=Ta(Sa)(...q);
n=V(n,h);h=b-1;if(!f.hasOwnProperty(m))throw new Fa("Replacing nonexistent public symbol");void 0!==f[m].B&&void 0!==h?f[m].B[h]=n:(f[m]=n,f[m].F=h);return[]})},b:(a,b,c,d,e)=>{b=O(b);-1===e&&(e=4294967295);e=g=>g;if(0===d){var k=32-8*c;e=g=>g<<k>>>k}var l=b.includes("unsigned")?function(g,m){return m>>>0}:function(g,m){return m};T(a,{name:b,fromWireType:e,toWireType:l,argPackAdvance:8,readValueFromPointer:fb(b,c,0!==d),C:null})},a:(a,b,c)=>{function d(k){return new e(ia.buffer,L[k+4>>2],L[k>>2])}
var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=O(c);T(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{G:!0})},e:(a,b)=>{b=O(b);var c="std::string"===b;T(a,{name:b,fromWireType:function(d){var e=L[d>>2],k=d+4;if(c)for(var l=k,g=0;g<=e;++g){var m=k+g;if(g==e||0==G[m]){if(l){var h=l;var n=G,q=h+(m-l);for(l=h;n[l]&&!(l>=q);)++l;if(16<l-h&&n.buffer&&gb)h=gb.decode(n.subarray(h,l));else{for(q="";h<l;){var p=n[h++];if(p&128){var w=
n[h++]&63;if(192==(p&224))q+=String.fromCharCode((p&31)<<6|w);else{var E=n[h++]&63;p=224==(p&240)?(p&15)<<12|w<<6|E:(p&7)<<18|w<<12|E<<6|n[h++]&63;65536>p?q+=String.fromCharCode(p):(p-=65536,q+=String.fromCharCode(55296|p>>10,56320|p&1023))}}else q+=String.fromCharCode(p)}h=q}}else h="";if(void 0===y)var y=h;else y+=String.fromCharCode(0),y+=h;l=m+1}}else{y=Array(e);for(g=0;g<e;++g)y[g]=String.fromCharCode(G[k+g]);y=y.join("")}W(d);return y},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));
var k,l="string"==typeof e;if(!(l||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array))throw new S("Cannot pass non-string to std::string");var g;if(c&&l)for(k=g=0;k<e.length;++k){var m=e.charCodeAt(k);127>=m?g++:2047>=m?g+=2:55296<=m&&57343>=m?(g+=4,++k):g+=3}else g=e.length;k=g;g=ub(4+k+1);m=g+4;L[g>>2]=k;if(c&&l){if(l=m,m=k+1,k=G,0<m){m=l+m-1;for(var h=0;h<e.length;++h){var n=e.charCodeAt(h);if(55296<=n&&57343>=n){var q=e.charCodeAt(++h);n=65536+((n&1023)<<10)|q&1023}if(127>=
n){if(l>=m)break;k[l++]=n}else{if(2047>=n){if(l+1>=m)break;k[l++]=192|n>>6}else{if(65535>=n){if(l+2>=m)break;k[l++]=224|n>>12}else{if(l+3>=m)break;k[l++]=240|n>>18;k[l++]=128|n>>12&63}k[l++]=128|n>>6&63}k[l++]=128|n&63}}k[l]=0}}else if(l)for(l=0;l<k;++l){h=e.charCodeAt(l);if(255<h)throw W(m),new S("String has UTF-16 code units that do not fit in 8 bits");G[m+l]=h}else for(l=0;l<k;++l)G[m+l]=e[l];null!==d&&d.push(W,g);return g},argPackAdvance:8,readValueFromPointer:Ma,C(d){W(d)}})},d:(a,b,c)=>{c=O(c);
if(2===b){var d=ib;var e=jb;var k=kb;var l=g=>I[g>>1]}else 4===b&&(d=lb,e=mb,k=nb,l=g=>L[g>>2]);T(a,{name:c,fromWireType:g=>{for(var m=L[g>>2],h,n=g+4,q=0;q<=m;++q){var p=g+4+q*b;if(q==m||0==l(p))n=d(n,p-n),void 0===h?h=n:(h+=String.fromCharCode(0),h+=n),n=p+b}W(g);return h},toWireType:(g,m)=>{if("string"!=typeof m)throw new S(`Cannot pass non-string to C++ string type ${c}`);var h=k(m),n=ub(4+h+b);L[n>>2]=h/b;e(m,n+4,h+b);null!==g&&g.push(W,n);return n},argPackAdvance:8,readValueFromPointer:Ma,C(g){W(g)}})},
l:a=>{T(a,Na)},k:(a,b)=>{b=O(b);T(a,{H:!0,name:b,argPackAdvance:0,fromWireType:()=>{},toWireType:()=>{}})},r:(a,b,c)=>G.copyWithin(a,b,b+c),u:(a,b,c,d)=>{a=ob[a];b=Ka(b);return a(null,b,c,d)},c:Ja,t:(a,b,c)=>{b=rb(a,b);var d=b.shift();a--;var e="return function (obj, func, destructorsRef, args) {\n",k=0,l=[];0===c&&l.push("obj");for(var g=["retType"],m=[d],h=0;h<a;++h)l.push("arg"+h),g.push("argType"+h),m.push(b[h]),e+=`  var arg${h} = argType${h}.readValueFromPointer(args${k?"+"+k:""});\n`,k+=b[h].argPackAdvance;
e+=`  var rv = ${1===c?"new func":"func.call"}(${l.join(", ")});\n`;d.H||(g.push("emval_returnValue"),m.push(sb),e+="  return emval_returnValue(retType, destructorsRef, rv);\n");g.push(e+"};\n");a=Ta(g)(...m);c=`methodCaller<(${b.map(n=>n.name).join(", ")}) => ${d.name}>`;return pb(V(c,a))},m:a=>{9<a&&(U[a+1]+=1)},s:a=>{var b=Ka(a);Pa(b);Ja(a)},f:(a,b)=>{a=qb(a,"_emval_take_value");a=a.readValueFromPointer(b);return La(a)},q:a=>{var b=G.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=
b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-F.buffer.byteLength+65535)/65536;try{F.grow(e);la();var k=1;break a}catch(l){}k=void 0}if(k)return!0}return!1}},Y=function(){function a(c){Y=c.exports;F=Y.v;la();Xa=Y.A;na.unshift(Y.w);M--;f.monitorRunDependencies?.(M);0==M&&(null!==ra&&(clearInterval(ra),ra=null),N&&(c=N,N=null,c()));return Y}var b={a:vb};M++;f.monitorRunDependencies?.(M);if(f.instantiateWasm)try{return f.instantiateWasm(b,
a)}catch(c){C(`Module.instantiateWasm callback failed with error: ${c}`),r(c)}ua||=f.locateFile?ta("silk.wasm")?"silk.wasm":f.locateFile?f.locateFile("silk.wasm",x):x+"silk.wasm":(new URL("silk.wasm",import.meta.url)).href;ya(b,function(c){a(c.instance)}).catch(r);return{}}(),bb=a=>(bb=Y.x)(a),ub=a=>(ub=Y.y)(a),W=a=>(W=Y.z)(a),Z;N=function xb(){Z||yb();Z||(N=xb)};
function yb(){function a(){if(!Z&&(Z=!0,f.calledRun=!0,!ha)){za(na);aa(f);f.onRuntimeInitialized?.();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();pa.unshift(b)}za(pa)}}if(!(0<M)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)qa();za(ma);0<M||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},1)):a())}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();yb();moduleRtn=ba;


  return moduleRtn;
}
);
})();
export default Module;
