
var Module = (() => {
  var _scriptName = import.meta.url;
  
  return (
async function(moduleArg = {}) {
  var moduleRtn;

var g=moduleArg,aa,q,ba=new Promise((a,b)=>{aa=a;q=b}),ca="object"==typeof window,da="function"==typeof importScripts,ea="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type;if(ea){const {createRequire:a}=await import("module");let b=import.meta.url;b.startsWith("data:")&&(b="/");var require=a(b)}var fa=Object.assign({},g),r=(a,b)=>{throw b;},t="",ha,w;
if(ea){var fs=require("fs"),ia=require("path");import.meta.url.startsWith("data:")||(t=ia.dirname(require("url").fileURLToPath(import.meta.url))+"/");w=a=>{a=y(a)?new URL(a):ia.normalize(a);return fs.readFileSync(a)};ha=a=>{a=y(a)?new URL(a):ia.normalize(a);return new Promise((b,c)=>{fs.readFile(a,void 0,(d,e)=>{d?c(d):b(e.buffer)})})};process.argv.slice(2);r=(a,b)=>{process.exitCode=a;throw b;}}else if(ca||da)da?t=self.location.href:"undefined"!=typeof document&&document.currentScript&&
(t=document.currentScript.src),_scriptName&&(t=_scriptName),t.startsWith("blob:")?t="":t=t.substr(0,t.replace(/[?#].*/,"").lastIndexOf("/")+1),da&&(w=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ha=a=>y(a)?new Promise((b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c(d.status)};d.onerror=c;d.send(null)}):fetch(a,{credentials:"same-origin"}).then(b=>
b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));g.print||console.log.bind(console);var z=g.printErr||console.error.bind(console);Object.assign(g,fa);fa=null;var A=g.wasmBinary,B,C=!1,ja,ka,E,F,G,H,I,la,ma;function na(){var a=B.buffer;g.HEAP8=ka=new Int8Array(a);g.HEAP16=F=new Int16Array(a);g.HEAPU8=E=new Uint8Array(a);g.HEAPU16=G=new Uint16Array(a);g.HEAP32=H=new Int32Array(a);g.HEAPU32=I=new Uint32Array(a);g.HEAPF32=la=new Float32Array(a);g.HEAPF64=ma=new Float64Array(a)}
var oa=[],pa=[],qa=[];function ra(){var a=g.preRun;a&&("function"==typeof a&&(a=[a]),a.forEach(sa));ta(oa)}function sa(a){oa.unshift(a)}function ua(a){qa.unshift(a)}var J=0,wa=null,K=null;function xa(a){g.onAbort?.(a);a="Aborted("+a+")";z(a);C=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");q(a);throw a;}var ya=a=>a.startsWith("data:application/octet-stream;base64,"),y=a=>a.startsWith("file://"),za;
function Aa(a){if(a==za&&A)return new Uint8Array(A);if(w)return w(a);throw"both async and sync fetching of the wasm failed";}function Ba(a){return A?Promise.resolve().then(()=>Aa(a)):ha(a).then(b=>new Uint8Array(b),()=>Aa(a))}function Ca(a,b,c){return Ba(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{z(`failed to asynchronously prepare wasm: ${d}`);xa(d)})}
function Da(a,b){var c=za;return A||"function"!=typeof WebAssembly.instantiateStreaming||ya(c)||y(c)||ea||"function"!=typeof fetch?Ca(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){z(`wasm streaming compile failed: ${e}`);z("falling back to ArrayBuffer instantiation");return Ca(c,a,b)}))}function Ea(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var ta=a=>{a.forEach(b=>b(g))},Fa=g.noExitRuntime||!0;class Ga{constructor(a){this.I=a-24}}
var Ha=0,Ia=0,Ja,L=a=>{for(var b="";E[a];)b+=Ja[E[a++]];return b},O={},P={},Q={},R,Ka=a=>{throw new R(a);},La,Ma=(a,b)=>{function c(f){f=b(f);if(f.length!==d.length)throw new La("Mismatched type converter count");for(var m=0;m<d.length;++m)S(d[m],f[m])}var d=[];d.forEach(f=>Q[f]=a);var e=Array(a.length),h=[],l=0;a.forEach((f,m)=>{P.hasOwnProperty(f)?e[m]=P[f]:(h.push(f),O.hasOwnProperty(f)||(O[f]=[]),O[f].push(()=>{e[m]=P[f];++l;l===h.length&&c(e)}))});0===h.length&&c(e)};
function Na(a,b,c={}){var d=b.name;if(!a)throw new R(`type "${d}" must have a positive integer typeid pointer`);if(P.hasOwnProperty(a)){if(c.K)return;throw new R(`Cannot register type '${d}' twice`);}P[a]=b;delete Q[a];O.hasOwnProperty(a)&&(b=O[a],delete O[a],b.forEach(e=>e()))}function S(a,b,c={}){return Na(a,b,c)}
var Oa=[],T=[],Pa=a=>{9<a&&0===--T[a+1]&&(T[a]=void 0,Oa.push(a))},Qa=a=>{if(!a)throw new R("Cannot use deleted val. handle = "+a);return T[a]},Ra=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Oa.pop()||T.length;T[b]=a;T[b+1]=1;return b}};function Sa(a){return this.fromWireType(I[a>>2])}
var Ta={name:"emscripten::val",fromWireType:a=>{var b=Qa(a);Pa(a);return b},toWireType:(a,b)=>Ra(b),H:8,readValueFromPointer:Sa,G:null},Ua=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(la[c>>2])};case 8:return function(c){return this.fromWireType(ma[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},U=(a,b)=>Object.defineProperty(b,"name",{value:a}),Va=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};
function Wa(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].G)return!0;return!1}function $a(a){var b=Function;if(!(b instanceof Function))throw new TypeError(`new_ called with constructor type ${typeof b} which is not a function`);var c=U(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
for(var ab=(a,b)=>{if(void 0===g[a].F){var c=g[a];g[a]=function(...d){if(!g[a].F.hasOwnProperty(d.length))throw new R(`Function '${b}' called with an invalid number of arguments (${d.length}) - expects one of (${g[a].F})!`);return g[a].F[d.length].apply(this,d)};g[a].F=[];g[a].F[c.J]=c}},bb=(a,b,c)=>{if(g.hasOwnProperty(a)){if(void 0===c||void 0!==g[a].F&&void 0!==g[a].F[c])throw new R(`Cannot register public name '${a}' twice`);ab(a,a);if(g[a].F.hasOwnProperty(c))throw new R(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
g[a].F[c]=b}else g[a]=b,g[a].J=c},cb=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(I[b+4*d>>2]);return c},db,eb=(a,b,c=[])=>{a.includes("j")?(a=a.replace(/p/g,"i"),b=(0,g["dynCall_"+a])(b,...c)):b=db.get(b)(...c);return b},fb=(a,b)=>(...c)=>eb(a,b,c),gb=(a,b)=>{a=L(a);var c=a.includes("j")?fb(a,b):db.get(b);if("function"!=typeof c)throw new R(`unknown function pointer with signature ${a}: ${b}`);return c},hb,jb=a=>{a=ib(a);var b=L(a);V(a);return b},kb=(a,b)=>{function c(h){e[h]||P[h]||(Q[h]?Q[h].forEach(c):
(d.push(h),e[h]=!0))}var d=[],e={};b.forEach(c);throw new hb(`${a}: `+d.map(jb).join([", "]));},lb=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?a.substr(0,b):a},mb=(a,b,c)=>{switch(b){case 1:return c?d=>ka[d]:d=>E[d];case 2:return c?d=>F[d>>1]:d=>G[d>>1];case 4:return c?d=>H[d>>2]:d=>I[d>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},nb="undefined"!=typeof TextDecoder?new TextDecoder:void 0,ob=(a=0,b=NaN)=>{var c=E,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.buffer&&
nb)return nb.decode(c.subarray(a,b));for(d="";a<b;){var e=c[a++];if(e&128){var h=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var l=c[a++]&63;e=224==(e&240)?(e&15)<<12|h<<6|l:(e&7)<<18|h<<12|l<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},pb="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,qb=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&G[c];)++c;c<<=1;if(32<
c-a&&pb)return pb.decode(E.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=F[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},rb=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)F[b>>1]=a.charCodeAt(e),b+=2;F[b>>1]=0;return b-d},sb=a=>2*a.length,tb=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=H[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},ub=(a,b,c)=>
{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var h=a.charCodeAt(e);if(55296<=h&&57343>=h){var l=a.charCodeAt(++e);h=65536+((h&1023)<<10)|l&1023}H[b>>2]=h;b+=4;if(b+4>c)break}H[b>>2]=0;return b-d},vb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},wb=[],xb=a=>{var b=wb.length;wb.push(a);return b},yb=(a,b)=>{var c=P[a];if(void 0===c)throw a=`${b} has unknown type ${jb(a)}`,new R(a);return c},zb=(a,b)=>{for(var c=Array(a),
d=0;d<a;++d)c[d]=yb(I[b+4*d>>2],"parameter "+d);return c},Ab=(a,b,c)=>{var d=[];a=a.toWireType(d,c);d.length&&(I[b>>2]=Ra(d));return a},W={},Bb=0,Cb=a=>{ja=a;Fa||0<Bb||(g.onExit?.(a),C=!0);r(a,new Ea(a))},Db=a=>{if(!C)try{if(a(),!(Fa||0<Bb))try{ja=a=ja,Cb(a)}catch(b){b instanceof Ea||"unwind"==b||r(1,b)}}catch(b){b instanceof Ea||"unwind"==b||r(1,b)}},Eb=Array(256),X=0;256>X;++X)Eb[X]=String.fromCharCode(X);Ja=Eb;R=g.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};
La=g.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};T.push(0,1,void 0,1,null,1,!0,1,!1,1);g.count_emval_handles=()=>T.length/2-5-Oa.length;
hb=g.UnboundTypeError=((a,b)=>{var c=U(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
var Hb={r:(a,b,c)=>{var d=new Ga(a);I[d.I+16>>2]=0;I[d.I+4>>2]=b;I[d.I+8>>2]=c;Ha=a;Ia++;throw Ha;},s:()=>{xa("")},n:()=>{},j:(a,b,c,d)=>{b=L(b);S(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,h){return h?c:d},H:8,readValueFromPointer:function(e){return this.fromWireType(E[e])},G:null})},i:a=>S(a,Ta),g:(a,b,c)=>{b=L(b);S(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,H:8,readValueFromPointer:Ua(b,c),G:null})},h:(a,b,c,d,e,h,l)=>{var f=cb(b,c);a=L(a);a=lb(a);e=gb(d,e);bb(a,function(){kb(`Cannot call ${a} due to unbound types`,
f)},b-1);Ma(f,m=>{var k=[m[0],null].concat(m.slice(1));m=a;var n=a;var v=e,p=k.length;if(2>p)throw new R("argTypes array size mismatch! Must at least get return value and 'this' types!");var D=null!==k[1]&&!1,M=Wa(k),Xa="void"!==k[0].name;v=[n,Ka,v,h,Va,k[0],k[1]];for(var x=0;x<p-2;++x)v.push(k[x+2]);if(!M)for(x=D?1:2;x<k.length;++x)null!==k[x].G&&v.push(k[x].G);M=Wa(k);x=k.length-2;var u=[],N=["fn"];D&&N.push("thisWired");for(p=0;p<x;++p)u.push(`arg${p}`),N.push(`arg${p}Wired`);u=u.join(",");N=N.join(",");
u=`return function (${u}) {\n`;M&&(u+="var destructors = [];\n");var Ya=M?"destructors":"null",va="humanName throwBindingError invoker fn runDestructors retType classParam".split(" ");D&&(u+=`var thisWired = classParam['toWireType'](${Ya}, this);\n`);for(p=0;p<x;++p)u+=`var arg${p}Wired = argType${p}['toWireType'](${Ya}, arg${p});\n`,va.push(`argType${p}`);u+=(Xa||l?"var rv = ":"")+`invoker(${N});\n`;if(M)u+="runDestructors(destructors);\n";else for(p=D?1:2;p<k.length;++p)D=1===p?"thisWired":"arg"+
(p-2)+"Wired",null!==k[p].G&&(u+=`${D}_dtor(${D});\n`,va.push(`${D}_dtor`));Xa&&(u+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");let [Za,Jb]=[va,u+"}\n"];Za.push(Jb);k=$a(Za)(...v);n=U(n,k);k=b-1;if(!g.hasOwnProperty(m))throw new La("Replacing nonexistent public symbol");void 0!==g[m].F&&void 0!==k?g[m].F[k]=n:(g[m]=n,g[m].J=k);return[]})},b:(a,b,c,d,e)=>{b=L(b);-1===e&&(e=4294967295);e=f=>f;if(0===d){var h=32-8*c;e=f=>f<<h>>>h}var l=b.includes("unsigned")?function(f,m){return m>>>0}:
function(f,m){return m};S(a,{name:b,fromWireType:e,toWireType:l,H:8,readValueFromPointer:mb(b,c,0!==d),G:null})},a:(a,b,c)=>{function d(h){return new e(ka.buffer,I[h+4>>2],I[h>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=L(c);S(a,{name:c,fromWireType:d,H:8,readValueFromPointer:d},{K:!0})},e:(a,b)=>{b=L(b);var c="std::string"===b;S(a,{name:b,fromWireType:function(d){var e=I[d>>2],h=d+4;if(c)for(var l=h,f=0;f<=e;++f){var m=h+f;if(f==
e||0==E[m]){l=l?ob(l,m-l):"";if(void 0===k)var k=l;else k+=String.fromCharCode(0),k+=l;l=m+1}}else{k=Array(e);for(f=0;f<e;++f)k[f]=String.fromCharCode(E[h+f]);k=k.join("")}V(d);return k},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var h,l="string"==typeof e;if(!(l||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array))throw new R("Cannot pass non-string to std::string");var f;if(c&&l)for(h=f=0;h<e.length;++h){var m=e.charCodeAt(h);127>=m?f++:
2047>=m?f+=2:55296<=m&&57343>=m?(f+=4,++h):f+=3}else f=e.length;h=f;f=Fb(4+h+1);m=f+4;I[f>>2]=h;if(c&&l){if(l=m,m=h+1,h=E,0<m){m=l+m-1;for(var k=0;k<e.length;++k){var n=e.charCodeAt(k);if(55296<=n&&57343>=n){var v=e.charCodeAt(++k);n=65536+((n&1023)<<10)|v&1023}if(127>=n){if(l>=m)break;h[l++]=n}else{if(2047>=n){if(l+1>=m)break;h[l++]=192|n>>6}else{if(65535>=n){if(l+2>=m)break;h[l++]=224|n>>12}else{if(l+3>=m)break;h[l++]=240|n>>18;h[l++]=128|n>>12&63}h[l++]=128|n>>6&63}h[l++]=128|n&63}}h[l]=0}}else if(l)for(l=
0;l<h;++l){k=e.charCodeAt(l);if(255<k)throw V(m),new R("String has UTF-16 code units that do not fit in 8 bits");E[m+l]=k}else for(l=0;l<h;++l)E[m+l]=e[l];null!==d&&d.push(V,f);return f},H:8,readValueFromPointer:Sa,G(d){V(d)}})},d:(a,b,c)=>{c=L(c);if(2===b){var d=qb;var e=rb;var h=sb;var l=f=>G[f>>1]}else 4===b&&(d=tb,e=ub,h=vb,l=f=>I[f>>2]);S(a,{name:c,fromWireType:f=>{for(var m=I[f>>2],k,n=f+4,v=0;v<=m;++v){var p=f+4+v*b;if(v==m||0==l(p))n=d(n,p-n),void 0===k?k=n:(k+=String.fromCharCode(0),k+=n),
n=p+b}V(f);return k},toWireType:(f,m)=>{if("string"!=typeof m)throw new R(`Cannot pass non-string to C++ string type ${c}`);var k=h(m),n=Fb(4+k+b);I[n>>2]=k/b;e(m,n+4,k+b);null!==f&&f.push(V,n);return n},H:8,readValueFromPointer:Sa,G(f){V(f)}})},l:a=>{S(a,Ta)},k:(a,b)=>{b=L(b);S(a,{L:!0,name:b,H:0,fromWireType:()=>{},toWireType:()=>{}})},u:(a,b,c)=>E.copyWithin(a,b,b+c),p:()=>{Fa=!1;Bb=0},x:(a,b,c,d)=>{a=wb[a];b=Qa(b);return a(null,b,c,d)},c:Pa,w:(a,b,c)=>{b=zb(a,b);var d=b.shift();a--;var e="return function (obj, func, destructorsRef, args) {\n",
h=0,l=[];0===c&&l.push("obj");for(var f=["retType"],m=[d],k=0;k<a;++k)l.push("arg"+k),f.push("argType"+k),m.push(b[k]),e+=`  var arg${k} = argType${k}.readValueFromPointer(args${h?"+"+h:""});\n`,h+=b[k].H;e+=`  var rv = ${1===c?"new func":"func.call"}(${l.join(", ")});\n`;d.L||(f.push("emval_returnValue"),m.push(Ab),e+="  return emval_returnValue(retType, destructorsRef, rv);\n");f.push(e+"};\n");a=$a(f)(...m);c=`methodCaller<(${b.map(n=>n.name).join(", ")}) => ${d.name}>`;return xb(U(c,a))},m:a=>
{9<a&&(T[a+1]+=1)},v:a=>{var b=Qa(a);Va(b);Pa(a)},f:(a,b)=>{a=yb(a,"_emval_take_value");a=a.readValueFromPointer(b);return Ra(a)},q:(a,b)=>{W[a]&&(clearTimeout(W[a].id),delete W[a]);if(!b)return 0;var c=setTimeout(()=>{delete W[a];Db(()=>Gb(a,performance.now()))},b);W[a]={id:c,M:b};return 0},t:a=>{var b=E.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-B.buffer.byteLength+65535)/
65536|0;try{B.grow(d);na();var e=1;break a}catch(h){}e=void 0}if(e)return!0}return!1},o:Cb},Y=function(){function a(c){Y=c.exports;B=Y.y;na();db=Y.E;pa.unshift(Y.z);J--;g.monitorRunDependencies?.(J);0==J&&(null!==wa&&(clearInterval(wa),wa=null),K&&(c=K,K=null,c()));return Y}var b={a:Hb};J++;g.monitorRunDependencies?.(J);if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){z(`Module.instantiateWasm callback failed with error: ${c}`),q(c)}za??=g.locateFile?ya("silk.wasm")?"silk.wasm":g.locateFile?
g.locateFile("silk.wasm",t):t+"silk.wasm":(new URL("silk.wasm",import.meta.url)).href;Da(b,function(c){a(c.instance)}).catch(q);return{}}(),ib=a=>(ib=Y.A)(a),Fb=a=>(Fb=Y.B)(a),V=a=>(V=Y.C)(a),Gb=(a,b)=>(Gb=Y.D)(a,b),Z,Ib;K=function Kb(){Z||Lb();Z||(K=Kb)};
function Lb(){function a(){if(!Z&&(Z=1,g.calledRun=1,!C)){ta(pa);aa(g);g.onRuntimeInitialized?.();var b=g.postRun;b&&("function"==typeof b&&(b=[b]),b.forEach(ua));ta(qa)}}if(!(0<J)){if(!Ib&&(Ib=1,ra(),0<J))return;g.setStatus?(g.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>g.setStatus(""),1);a()},1)):a()}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();Lb();moduleRtn=ba;


  return moduleRtn;
}
);
})();
export default Module;
