var Module = (() => {
  
  return (
async function(moduleArg = {}) {
  var moduleRtn;

var g=moduleArg,aa,q,ba=new Promise((a,b)=>{aa=a;q=b}),ca="object"==typeof window,da="undefined"!=typeof WorkerGlobalScope,t="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type;if(t){const {createRequire:a}=await import("module");var require=a(import.meta.url)}var u=(a,b)=>{throw b;},ea=import.meta.url,v="",fa,w;
if(t){var fs=require("fs"),ha=require("path");ea.startsWith("file:")&&(v=ha.dirname(require("url").fileURLToPath(ea))+"/");w=a=>{a=y(a)?new URL(a):a;return fs.readFileSync(a)};fa=async a=>{a=y(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.slice(2);u=(a,b)=>{process.exitCode=a;throw b;}}else if(ca||da){try{v=(new URL(".",ea)).href}catch{}da&&(w=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});fa=async a=>
{if(y(a))return new Promise((d,c)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?d(e.response):c(e.status)};e.onerror=c;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}console.log.bind(console);var A=console.error.bind(console),C,D,E=!1,ia,ja,F,G,H,I,J,ka,la,ma,na,y=a=>a.startsWith("file://");
function pa(){var a=D.buffer;ja=new Int8Array(a);G=new Int16Array(a);F=new Uint8Array(a);H=new Uint16Array(a);I=new Int32Array(a);J=new Uint32Array(a);ka=new Float32Array(a);na=new Float64Array(a);la=new BigInt64Array(a);ma=new BigUint64Array(a)}var K=0,L=null;function qa(a){g.onAbort?.(a);a="Aborted("+a+")";A(a);E=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");q(a);throw a;}var ra;
async function sa(a){if(!C)try{var b=await fa(a);return new Uint8Array(b)}catch{}if(a==ra&&C)a=new Uint8Array(C);else if(w)a=w(a);else throw"both async and sync fetching of the wasm failed";return a}async function ta(a,b){try{var d=await sa(a);return await WebAssembly.instantiate(d,b)}catch(c){A(`failed to asynchronously prepare wasm: ${c}`),qa(c)}}
async function ua(a){var b=ra;if(!C&&"function"==typeof WebAssembly.instantiateStreaming&&!y(b)&&!t)try{var d=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(d,a)}catch(c){A(`wasm streaming compile failed: ${c}`),A("falling back to ArrayBuffer instantiation")}return ta(b,a)}class va{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var wa=a=>{for(;0<a.length;)a.shift()(g)},xa=[],ya=[],za=()=>{var a=g.preRun.shift();ya.push(a)},O=!0;class Aa{constructor(a){this.I=a-24}}var Ba=0,Ca=0,Da,P=a=>{for(var b="";F[a];)b+=Da[F[a++]];return b},Q={},R={},S={},T=g.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}},Ea=a=>{throw new T(a);};
function Fa(a,b,d={}){var c=b.name;if(!a)throw new T(`type "${c}" must have a positive integer typeid pointer`);if(R.hasOwnProperty(a)){if(d.K)return;throw new T(`Cannot register type '${c}' twice`);}R[a]=b;delete S[a];Q.hasOwnProperty(a)&&(b=Q[a],delete Q[a],b.forEach(e=>e()))}function U(a,b,d={}){return Fa(a,b,d)}
var Ga=(a,b,d)=>{switch(b){case 1:return d?c=>ja[c]:c=>F[c];case 2:return d?c=>G[c>>1]:c=>H[c>>1];case 4:return d?c=>I[c>>2]:c=>J[c>>2];case 8:return d?c=>la[c>>3]:c=>ma[c>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Ha=[],V=[],Ia=a=>{9<a&&0===--V[a+1]&&(V[a]=void 0,Ha.push(a))},Ja=a=>{if(!a)throw new T(`Cannot use deleted val. handle = ${a}`);return V[a]},Ka=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Ha.pop()||
V.length;V[b]=a;V[b+1]=1;return b}};function La(a){return this.fromWireType(J[a>>2])}var Ma={name:"emscripten::val",fromWireType:a=>{var b=Ja(a);Ia(a);return b},toWireType:(a,b)=>Ka(b),H:8,readValueFromPointer:La,G:null},Na=(a,b)=>{switch(b){case 4:return function(d){return this.fromWireType(ka[d>>2])};case 8:return function(d){return this.fromWireType(na[d>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Oa=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};
function Pa(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].G)return!0;return!1}
var Sa=(a,b)=>{if(void 0===g[a].F){var d=g[a];g[a]=function(...c){if(!g[a].F.hasOwnProperty(c.length))throw new T(`Function '${b}' called with an invalid number of arguments (${c.length}) - expects one of (${g[a].F})!`);return g[a].F[c.length].apply(this,c)};g[a].F=[];g[a].F[d.J]=d}},Ta=(a,b,d)=>{if(g.hasOwnProperty(a)){if(void 0===d||void 0!==g[a].F&&void 0!==g[a].F[d])throw new T(`Cannot register public name '${a}' twice`);Sa(a,a);if(g[a].F.hasOwnProperty(d))throw new T(`Cannot register multiple overloads of a function with the same number of arguments (${d})!`);
g[a].F[d]=b}else g[a]=b,g[a].J=d},Ua=(a,b)=>{for(var d=[],c=0;c<a;c++)d.push(J[b+4*c>>2]);return d},Va=g.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}},Wa=[],Xa,Ya=(a,b)=>{a=P(a);var d;(d=Wa[b])||(Wa[b]=d=Xa.get(b));if("function"!=typeof d)throw new T(`unknown function pointer with signature ${a}: ${b}`);return d};class Za extends Error{}
for(var ab=a=>{a=$a(a);var b=P(a);W(a);return b},bb=(a,b)=>{function d(f){e[f]||R[f]||(S[f]?S[f].forEach(d):(c.push(f),e[f]=!0))}var c=[],e={};b.forEach(d);throw new Za(`${a}: `+c.map(ab).join([", "]));},cb=(a,b)=>{function d(h){h=b(h);if(h.length!==c.length)throw new Va("Mismatched type converter count");for(var l=0;l<c.length;++l)U(c[l],h[l])}var c=[];c.forEach(h=>S[h]=a);var e=Array(a.length),f=[],m=0;a.forEach((h,l)=>{R.hasOwnProperty(h)?e[l]=R[h]:(f.push(h),Q.hasOwnProperty(h)||(Q[h]=[]),Q[h].push(()=>
{e[l]=R[h];++m;m===f.length&&d(e)}))});0===f.length&&d(e)},db=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},eb="undefined"!=typeof TextDecoder?new TextDecoder:void 0,fb=(a=0,b=NaN)=>{var d=F,c=a+b;for(b=a;d[b]&&!(b>=c);)++b;if(16<b-a&&d.buffer&&eb)return eb.decode(d.subarray(a,b));for(c="";a<b;){var e=d[a++];if(e&128){var f=d[a++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|f);else{var m=d[a++]&63;e=224==(e&240)?(e&15)<<12|f<<6|m:(e&7)<<18|f<<12|m<<6|d[a++]&63;65536>e?
c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},gb="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,hb=(a,b)=>{var d=a>>1;for(var c=d+b/2;!(d>=c)&&H[d];)++d;d<<=1;if(32<d-a&&gb)return gb.decode(F.subarray(a,d));d="";for(c=0;!(c>=b/2);++c){var e=G[a+2*c>>1];if(0==e)break;d+=String.fromCharCode(e)}return d},ib=(a,b,d)=>{d??=2147483647;if(2>d)return 0;d-=2;var c=b;d=d<2*a.length?d/2:a.length;for(var e=0;e<
d;++e)G[b>>1]=a.charCodeAt(e),b+=2;G[b>>1]=0;return b-c},jb=a=>2*a.length,kb=(a,b)=>{for(var d=0,c="";!(d>=b/4);){var e=I[a+4*d>>2];if(0==e)break;++d;65536<=e?(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023)):c+=String.fromCharCode(e)}return c},lb=(a,b,d)=>{d??=2147483647;if(4>d)return 0;var c=b;d=c+d-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var m=a.charCodeAt(++e);f=65536+((f&1023)<<10)|m&1023}I[b>>2]=f;b+=4;if(b+4>d)break}I[b>>2]=0;return b-c},mb=a=>{for(var b=
0,d=0;d<a.length;++d){var c=a.charCodeAt(d);55296<=c&&57343>=c&&++d;b+=4}return b},nb=0,ob=[],pb=a=>{var b=ob.length;ob.push(a);return b},qb=(a,b)=>{var d=R[a];if(void 0===d)throw a=`${b} has unknown type ${ab(a)}`,new T(a);return d},rb=(a,b)=>{for(var d=Array(a),c=0;c<a;++c)d[c]=qb(J[b+4*c>>2],`parameter ${c}`);return d},sb=(a,b,d)=>{var c=[];a=a.toWireType(c,d);c.length&&(J[b>>2]=Ka(c));return a},X={},tb=a=>{ia=a;O||0<nb||(g.onExit?.(a),E=!0);u(a,new va(a))},ub=a=>{if(!E)try{if(a(),!(O||0<nb))try{ia=
a=ia,tb(a)}catch(b){b instanceof va||"unwind"==b||u(1,b)}}catch(b){b instanceof va||"unwind"==b||u(1,b)}},vb=Array(256),Y=0;256>Y;++Y)vb[Y]=String.fromCharCode(Y);Da=vb;V.push(0,1,void 0,1,null,1,!0,1,!1,1);g.count_emval_handles=()=>V.length/2-5-Ha.length;g.noExitRuntime&&(O=g.noExitRuntime);g.printErr&&(A=g.printErr);g.wasmBinary&&(C=g.wasmBinary);
var Ab={u:(a,b,d)=>{var c=new Aa(a);J[c.I+16>>2]=0;J[c.I+4>>2]=b;J[c.I+8>>2]=d;Ba=a;Ca++;throw Ba;},v:()=>qa(""),l:(a,b,d)=>{b=P(b);U(a,{name:b,fromWireType:c=>c,toWireType:function(c,e){if("bigint"!=typeof e&&"number"!=typeof e)throw null===e?e="null":(c=typeof e,e="object"===c||"array"===c||"function"===c?e.toString():""+e),new TypeError(`Cannot convert "${e}" to ${this.name}`);"number"==typeof e&&(e=BigInt(e));return e},H:8,readValueFromPointer:Ga(b,d,-1==b.indexOf("u")),G:null})},o:(a,b,d,c)=>
{b=P(b);U(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,f){return f?d:c},H:8,readValueFromPointer:function(e){return this.fromWireType(F[e])},G:null})},m:a=>U(a,Ma),k:(a,b,d)=>{b=P(b);U(a,{name:b,fromWireType:c=>c,toWireType:(c,e)=>e,H:8,readValueFromPointer:Na(b,d),G:null})},c:(a,b,d,c,e,f,m)=>{var h=Ua(b,d);a=P(a);a=db(a);e=Ya(c,e);Ta(a,function(){bb(`Cannot call ${a} due to unbound types`,h)},b-1);cb(h,l=>{var k=[l[0],null].concat(l.slice(1));l=a;var p=a;var z=e,n=k.length;
if(2>n)throw new T("argTypes array size mismatch! Must at least get return value and 'this' types!");var B=null!==k[1]&&!1,M=Pa(k),Qa="void"!==k[0].name;z=[p,Ea,z,f,Oa,k[0],k[1]];for(var x=0;x<n-2;++x)z.push(k[x+2]);if(!M)for(x=B?1:2;x<k.length;++x)null!==k[x].G&&z.push(k[x].G);M=Pa(k);x=k.length-2;var r=[],N=["fn"];B&&N.push("thisWired");for(n=0;n<x;++n)r.push(`arg${n}`),N.push(`arg${n}Wired`);r=r.join(",");N=N.join(",");r=`return function (${r}) {\n`;M&&(r+="var destructors = [];\n");var Ra=M?"destructors":
"null",oa="humanName throwBindingError invoker fn runDestructors retType classParam".split(" ");B&&(r+=`var thisWired = classParam['toWireType'](${Ra}, this);\n`);for(n=0;n<x;++n)r+=`var arg${n}Wired = argType${n}['toWireType'](${Ra}, arg${n});\n`,oa.push(`argType${n}`);r+=(Qa||m?"var rv = ":"")+`invoker(${N});\n`;if(M)r+="runDestructors(destructors);\n";else for(n=B?1:2;n<k.length;++n)B=1===n?"thisWired":"arg"+(n-2)+"Wired",null!==k[n].G&&(r+=`${B}_dtor(${B});\n`,oa.push(`${B}_dtor`));Qa&&(r+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");
let [yb,zb]=[oa,r+"}\n"];k=(new Function(...yb,zb))(...z);p=Object.defineProperty(k,"name",{value:p});k=b-1;if(!g.hasOwnProperty(l))throw new Va("Replacing nonexistent public symbol");void 0!==g[l].F&&void 0!==k?g[l].F[k]=p:(g[l]=p,g[l].J=k);return[]})},b:(a,b,d,c,e)=>{b=P(b);-1===e&&(e=4294967295);e=h=>h;if(0===c){var f=32-8*d;e=h=>h<<f>>>f}var m=b.includes("unsigned")?function(h,l){return l>>>0}:function(h,l){return l};U(a,{name:b,fromWireType:e,toWireType:m,H:8,readValueFromPointer:Ga(b,d,0!==
c),G:null})},a:(a,b,d)=>{function c(f){return new e(ja.buffer,J[f+4>>2],J[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];d=P(d);U(a,{name:d,fromWireType:c,H:8,readValueFromPointer:c},{K:!0})},n:(a,b)=>{b=P(b);U(a,{name:b,fromWireType:function(d){for(var c=J[d>>2],e=d+4,f,m=e,h=0;h<=c;++h){var l=e+h;if(h==c||0==F[l])m=m?fb(m,l-m):"",void 0===f?f=m:(f+=String.fromCharCode(0),f+=m),m=l+1}W(d);return f},toWireType:function(d,
c){c instanceof ArrayBuffer&&(c=new Uint8Array(c));var e,f="string"==typeof c;if(!(f||ArrayBuffer.isView(c)&&1==c.BYTES_PER_ELEMENT))throw new T("Cannot pass non-string to std::string");var m;if(f)for(e=m=0;e<c.length;++e){var h=c.charCodeAt(e);127>=h?m++:2047>=h?m+=2:55296<=h&&57343>=h?(m+=4,++e):m+=3}else m=c.length;e=m;m=wb(4+e+1);h=m+4;J[m>>2]=e;if(f){if(f=h,h=e+1,e=F,0<h){h=f+h-1;for(var l=0;l<c.length;++l){var k=c.charCodeAt(l);if(55296<=k&&57343>=k){var p=c.charCodeAt(++l);k=65536+((k&1023)<<
10)|p&1023}if(127>=k){if(f>=h)break;e[f++]=k}else{if(2047>=k){if(f+1>=h)break;e[f++]=192|k>>6}else{if(65535>=k){if(f+2>=h)break;e[f++]=224|k>>12}else{if(f+3>=h)break;e[f++]=240|k>>18;e[f++]=128|k>>12&63}e[f++]=128|k>>6&63}e[f++]=128|k&63}}e[f]=0}}else F.set(c,h);null!==d&&d.push(W,m);return m},H:8,readValueFromPointer:La,G(d){W(d)}})},e:(a,b,d)=>{d=P(d);if(2===b){var c=hb;var e=ib;var f=jb;var m=h=>H[h>>1]}else 4===b&&(c=kb,e=lb,f=mb,m=h=>J[h>>2]);U(a,{name:d,fromWireType:h=>{for(var l=J[h>>2],k,
p=h+4,z=0;z<=l;++z){var n=h+4+z*b;if(z==l||0==m(n))p=c(p,n-p),void 0===k?k=p:(k+=String.fromCharCode(0),k+=p),p=n+b}W(h);return k},toWireType:(h,l)=>{if("string"!=typeof l)throw new T(`Cannot pass non-string to C++ string type ${d}`);var k=f(l),p=wb(4+k+b);J[p>>2]=k/b;e(l,p+4,k+b);null!==h&&h.push(W,p);return p},H:8,readValueFromPointer:La,G(h){W(h)}})},f:a=>{U(a,Ma)},p:(a,b)=>{b=P(b);U(a,{L:!0,name:b,H:0,fromWireType:()=>{},toWireType:()=>{}})},s:()=>{O=!1;nb=0},i:(a,b,d,c)=>{a=ob[a];b=Ja(b);return a(null,
b,d,c)},d:Ia,h:(a,b,d)=>{b=rb(a,b);var c=b.shift();a--;var e="return function (obj, func, destructorsRef, args) {\n",f=0,m=[];0===d&&m.push("obj");for(var h=["retType"],l=[c],k=0;k<a;++k)m.push(`arg${k}`),h.push(`argType${k}`),l.push(b[k]),e+=`  var arg${k} = argType${k}.readValueFromPointer(args${f?"+"+f:""});\n`,f+=b[k].H;e+=`  var rv = ${1===d?"new func":"func.call"}(${m.join(", ")});\n`;c.L||(h.push("emval_returnValue"),l.push(sb),e+="  return emval_returnValue(retType, destructorsRef, rv);\n");
a=(new Function(...h,e+"};\n"))(...l);d=`methodCaller<(${b.map(p=>p.name).join(", ")}) => ${c.name}>`;return pb(Object.defineProperty(a,"name",{value:d}))},q:a=>{9<a&&(V[a+1]+=1)},g:a=>{var b=Ja(a);Oa(b);Ia(a)},j:(a,b)=>{a=qb(a,"_emval_take_value");a=a.readValueFromPointer(b);return Ka(a)},t:(a,b)=>{X[a]&&(clearTimeout(X[a].id),delete X[a]);if(!b)return 0;var d=setTimeout(()=>{delete X[a];ub(()=>xb(a,performance.now()))},b);X[a]={id:d,M:b};return 0},w:a=>{var b=F.length;a>>>=0;if(2147483648<a)return!1;
for(var d=1;4>=d;d*=2){var c=b*(1+.2/d);c=Math.min(c,a+100663296);a:{c=(Math.min(2147483648,65536*Math.ceil(Math.max(a,c)/65536))-D.buffer.byteLength+65535)/65536|0;try{D.grow(c);pa();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},r:tb},Z=await (async function(){function a(c){Z=c.exports;D=Z.x;pa();Xa=Z.D;K--;g.monitorRunDependencies?.(K);0==K&&L&&(c=L,L=null,c());return Z}K++;g.monitorRunDependencies?.(K);var b={a:Ab};if(g.instantiateWasm)return new Promise(c=>{g.instantiateWasm(b,
(e,f)=>{c(a(e,f))})});ra??=g.locateFile?g.locateFile?g.locateFile("silk.wasm",v):v+"silk.wasm":(new URL("silk.wasm",import.meta.url)).href;try{var d=await ua(b);return a(d.instance)}catch(c){return q(c),Promise.reject(c)}}()),$a=Z.z,wb=Z.A,W=Z.B,xb=Z.C;
function Bb(){function a(){g.calledRun=!0;if(!E){Z.y();aa(g);g.onRuntimeInitialized?.();if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();xa.push(b)}wa(xa)}}if(0<K)L=Bb;else{if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)za();wa(ya);0<K?L=Bb:g.setStatus?(g.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>g.setStatus(""),1);a()},1)):a()}}
if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.shift()();Bb();moduleRtn=ba;


  return moduleRtn;
}
);
})();
export default Module;
